export const SET_AUTH_DATA = 'SET_AUTH_DATA';
export const REMOVE_AUTH_DATA = 'REMOVE_AUTH_DATA';

export const SET_AUTHORS = 'SET_AUTHORS';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const SET_CURRENT_VALUES = 'SET_CURRENT_VALUES';

