export const SET_AUTH_DATA = 'SET_AUTH_DATA';
export const REMOVE_AUTH_DATA = 'REMOVE_AUTH_DATA';

export const SET_AUTHORS = 'SET_AUTHORS';
export const SET_AUTHOR_RATING = 'SET_AUTHOR_RATING';
export const SET_FAVORITE_AUTHORS = 'SET_FAVORITE_AUTHORS';
export const SET_CURRENT_VALUES = 'SET_CURRENT_VALUES';

