export const SET_AUTH_DATA = 'SET_AUTH_DATA';
export const REMOVE_AUTH_DATA = 'REMOVE_AUTH_DATA';

export const SET_AUTHORS = 'SET_AUTHORS';
export const SET_FAVORITE_STATUS = 'SET_FAVORITE_STATUS';
export const SET_CURRENT_VALUES = 'SET_CURRENT_VALUES';

